<?php

$this->_troop_types = [
    1 => [
        "name" => clienttranslate("Skully"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate("<span style=\"font-weight: bold;\">Remark</span>: If you want to do this, wait until the other player has their 5 hand cards for the round. Then put one of your hand cards face up on the discard pile and put the top card from the draw deck in your hand."),
    ],

    2 => [
        "name" => clienttranslate("Cap'Taine"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate("<span style=\"font-weight: bold;\">Remark</span>: If you want to do this, wait until the other player has their 5 hand cards for the round. Then put one of your hand cards face up on the discard pile and put the top card from the draw deck in your hand."),
    ],

    3 => [
        "name" => clienttranslate("Mastok"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate("<span style=\"font-weight: bold;\">Remark</span>: If you want to do this, wait until the other player has their 5 hand cards for the round. Then put one of your hand cards face up on the discard pile and put the top card from the draw deck in your hand."),
    ],

    4 => [
        "name" => clienttranslate("Crochet"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate("<span style=\"font-weight: bold;\">Remark</span>: If you want to do this, wait until the other player has their 5 hand cards for the round. Then put one of your hand cards face up on the discard pile and put the top card from the draw deck in your hand."),
    ],

    5 => [
        "name" => clienttranslate("XB-42"),
        "desc1" => clienttranslate("<span style=\"font-weight: bold;\">Remark</span>: At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate(""),
    ],

    6 => [
        "name" => clienttranslate("Star"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate(""),
    ],

    7 => [
        "name" => clienttranslate("Roxy"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate(""),
    ],

    8 => [
        "name" => clienttranslate("Kwak"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate(""),
    ],
];


$this->_board_types = [
    1 => [
        "name" => clienttranslate("Castle"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate(""),
    ],
    2 => [
        "name" => clienttranslate("Clouds"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate(""),
    ],
    3 => [
        "name" => clienttranslate("Volcano"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate("If you want to do this, wait until the other player has their 5 hand cards for the round. Then put one of your hand cards face up on the discard pile and put the top card from the draw deck in your hand."),
    ],
    4 => [
        "name" => clienttranslate("Cemetery"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate(""),
    ],
    5 => [
        "name" => clienttranslate("Carribean"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate(""),
    ],
    6 => [
        "name" => clienttranslate("Battlefield"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate("If you want to do this, wait until the other player has their 5 hand cards for the round. Then put one of your hand cards face up on the discard pile and put the top card from the draw deck in your hand."),
    ],
    7 => [
        "name" => clienttranslate("Tropico"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate(""),
    ],
    8 => [
        "name" => clienttranslate("Metal"),
        "desc1" => clienttranslate("At the end of the Card Phase of <span style=\"font-weight: bold;\">each year</span>: You may discard 1 card from your hand and draw 1 new card."),
        "desc2" => clienttranslate(""),
    ],
];


$this->_bases = [
    "castle" => [
        1  => ["value" => 1,  "adjacents" => [11, 12],         "power" => 0, "top" => 87.5,  "left" => 43.2],
        11 => ["value" => 11, "adjacents" => [1, 13],          "power" => 0, "top" => 84.9,  "left" => 10.2],
        12 => ["value" => 12, "adjacents" => [1, 14],          "power" => 0, "top" => 84.9,  "left" => 76.6],
        13 => ["value" => 13, "adjacents" => [11, 15, 17, 18], "power" => 0, "top" => 70.5,  "left" => 30.4],
        14 => ["value" => 14, "adjacents" => [12, 16, 18, 19], "power" => 0, "top" => 70.6,  "left" => 56],
        15 => ["value" => 15, "adjacents" => [13, 17],         "power" => 11, "top" => 63.2, "left" => 8.1],
        16 => ["value" => 16, "adjacents" => [14, 19],         "power" => 11, "top" => 63.2, "left" => 79.1],
        17 => ["value" => 17, "adjacents" => [13, 15, 20, 22], "power" => 0, "top" => 44.2,  "left" => 13],
        18 => ["value" => 18, "adjacents" => [13, 14, 22, 23], "power" => 0, "top" => 44.2,  "left" => 43.4],
        19 => ["value" => 19, "adjacents" => [14, 16, 21, 23], "power" => 0, "top" => 44.2,  "left" => 73.8],
        20 => ["value" => 20, "adjacents" => [17, 22],         "power" => 11, "top" => 25,   "left" => 7.8],
        21 => ["value" => 21, "adjacents" => [19, 23],         "power" => 11, "top" => 25,   "left" => 78.8],
        22 => ["value" => 22, "adjacents" => [17, 18, 20, 24], "power" => 0, "top" => 15.8,  "left" => 30.6],
        23 => ["value" => 23, "adjacents" => [18, 19, 21, 25], "power" => 0, "top" => 15.8,  "left" => 56.2],
        24 => ["value" => 24, "adjacents" => [22, 41],         "power" => 0, "top" => 1.5,   "left" => 10.4],
        25 => ["value" => 25, "adjacents" => [23, 41],         "power" => 0, "top" => 1.5,   "left" => 76.8],
        41 => ["value" => 41, "adjacents" => [24, 25],         "power" => 0, "top" => 1.4,   "left" => 43.2],
    ],
    "pool" => [
        1  => ["value" => 1,  "adjacents" => [11],                     "power" => 0,  "top" => 82.1, "left" => 10.4],
        2  => ["value" => 2,  "adjacents" => [13],                     "power" => 26, "top" => 82.1, "left" => 78.2],
        11 => ["value" => 11, "adjacents" => [1, 12, 13],              "power" => 0,  "top" => 81.9, "left" => 43.4],
        12 => ["value" => 12, "adjacents" => [11, 13, 15],             "power" => 21, "top" => 67.4, "left" => 10.6],
        13 => ["value" => 13, "adjacents" => [2, 11, 12, 14, 17],      "power" => 0,  "top" => 65.6, "left" => 43.2],
        14 => ["value" => 14, "adjacents" => [13, 16, 17],             "power" => 0,  "top" => 67.4, "left" => 76],
        15 => ["value" => 15, "adjacents" => [12, 17, 18],             "power" => 0,  "top" => 52.4, "left" => 12.8],
        16 => ["value" => 16, "adjacents" => [14, 19],                 "power" => 23, "top" => 50.8, "left" => 77.3],
        17 => ["value" => 17, "adjacents" => [13, 14, 15, 19, 20, 21], "power" => 26, "top" => 44.8, "left" => 43.4],
        18 => ["value" => 18, "adjacents" => [15, 20],                 "power" => 23, "top" => 37.4, "left" => 9.7],
        19 => ["value" => 19, "adjacents" => [16, 17, 22],             "power" => 0,  "top" => 35.5, "left" => 76],
        20 => ["value" => 20, "adjacents" => [17, 18, 21],             "power" => 0,  "top" => 21.4, "left" => 10.4],
        21 => ["value" => 21, "adjacents" => [17, 20, 22, 23, 41],     "power" => 0,  "top" => 22.9, "left" => 44.7],
        22 => ["value" => 22, "adjacents" => [19, 21, 23],             "power" => 21, "top" => 20.6, "left" => 77.1],
        23 => ["value" => 23, "adjacents" => [21, 22, 42],             "power" => 0,  "top" => 6.4, "left" => 44.7],
        41 => ["value" => 41, "adjacents" => [21],                     "power" => 26, "top" => 5.6, "left" => 9.1],
        42 => ["value" => 42, "adjacents" => [23],                     "power" => 0,  "top" => 5.8, "left" => 77.5],
    ],
    "clouds" => [
        1  => ["value" => 1,  "adjacents" => [11, 12],         "power" => 0,  "top" => 86.6, "left" => 43.1],
        11 => ["value" => 11, "adjacents" => [1, 13, 14],      "power" => 0,  "top" => 79.4, "left" => 4.6],
        12 => ["value" => 12, "adjacents" => [1, 13, 15],      "power" => 0,  "top" => 79.4, "left" => 82.6],
        13 => ["value" => 13, "adjacents" => [11, 12, 14, 15], "power" => 31, "top" => 70.1, "left" => 43.4],
        14 => ["value" => 14, "adjacents" => [11, 13, 16, 17], "power" => 0,  "top" => 61.7, "left" => 4.6],
        15 => ["value" => 15, "adjacents" => [12, 13, 16, 18], "power" => 0,  "top" => 61.7, "left" => 82.6],
        16 => ["value" => 16, "adjacents" => [14, 15, 17, 18], "power" => 31, "top" => 52.3, "left" => 43.4],
        17 => ["value" => 17, "adjacents" => [14, 16, 19, 20], "power" => 0,  "top" => 44.3, "left" => 4.6],
        18 => ["value" => 18, "adjacents" => [15, 16, 19, 21], "power" => 0,  "top" => 44.3, "left" => 82.6],
        19 => ["value" => 19, "adjacents" => [17, 18, 20, 21], "power" => 31, "top" => 34.6, "left" => 43.4],
        20 => ["value" => 20, "adjacents" => [17, 19, 22, 23], "power" => 0,  "top" => 26.7, "left" => 4.6],
        21 => ["value" => 21, "adjacents" => [18, 19, 22, 24], "power" => 0,  "top" => 26.7, "left" => 82.6],
        22 => ["value" => 22, "adjacents" => [20, 21, 23, 24], "power" => 31, "top" => 17.2, "left" => 43.4],
        23 => ["value" => 23, "adjacents" => [20, 22, 41],     "power" => 0,  "top" => 9.1, "left" => 4.6],
        24 => ["value" => 24, "adjacents" => [21, 22, 41],     "power" => 0,  "top" => 9.1, "left" => 82.6],
        41 => ["value" => 41, "adjacents" => [23, 24],         "power" => 0,  "top" => 0.2, "left" => 43.4],
    ],
    "jungle" => [
        1  => ["value" => 1,  "adjacents" => [11, 13],         "power" => 0,  "top" => 0, "left" => 0],
        11 => ["value" => 11, "adjacents" => [1, 12, 13, 14],  "power" => 0,  "top" => 0, "left" => 0],
        12 => ["value" => 12, "adjacents" => [11, 15],         "power" => 0,  "top" => 0, "left" => 0],
        13 => ["value" => 13, "adjacents" => [1, 11, 16],      "power" => 0,  "top" => 0, "left" => 0],
        14 => ["value" => 14, "adjacents" => [11, 15, 17],     "power" => 0,  "top" => 0, "left" => 0],
        15 => ["value" => 15, "adjacents" => [12, 14, 18],     "power" => 41, "top" => 0, "left" => 0],
        16 => ["value" => 16, "adjacents" => [13, 17, 19],     "power" => 0,  "top" => 0, "left" => 0],
        17 => ["value" => 17, "adjacents" => [14, 16, 18, 20], "power" => 0,  "top" => 0, "left" => 0],
        18 => ["value" => 18, "adjacents" => [15, 17, 21],     "power" => 0,  "top" => 0, "left" => 0],
        19 => ["value" => 19, "adjacents" => [16, 20, 22],     "power" => 41, "top" => 0, "left" => 0],
        20 => ["value" => 20, "adjacents" => [17, 19, 23],     "power" => 0,  "top" => 0, "left" => 0],
        21 => ["value" => 21, "adjacents" => [18, 23, 41],     "power" => 0,  "top" => 0, "left" => 0],
        22 => ["value" => 22, "adjacents" => [19, 23],         "power" => 0,  "top" => 0, "left" => 0],
        23 => ["value" => 23, "adjacents" => [20, 21, 22, 41], "power" => 0,  "top" => 0, "left" => 0],
        41 => ["value" => 41, "adjacents" => [21, 23],         "power" => 0,  "top" => 0, "left" => 0],
    ],
    "cemetery" => [
        1  => ["value" => 1,  "adjacents" => [11, 13],             "power" => 0,  "top" => 0, "left" => 0],
        11 => ["value" => 11, "adjacents" => [1, 13, 14, 16],      "power" => 0,  "top" => 0, "left" => 0],
        12 => ["value" => 12, "adjacents" => [13, 15],             "power" => 51, "top" => 0, "left" => 0],
        13 => ["value" => 13, "adjacents" => [1, 11, 12, 15],      "power" => 0,  "top" => 0, "left" => 0],
        14 => ["value" => 14, "adjacents" => [11, 16],             "power" => 51, "top" => 0, "left" => 0],
        15 => ["value" => 15, "adjacents" => [12, 13, 16, 17, 18], "power" => 0,  "top" => 0, "left" => 0],
        16 => ["value" => 16, "adjacents" => [11, 14, 15, 18, 19], "power" => 0,  "top" => 0, "left" => 0],
        17 => ["value" => 17, "adjacents" => [15, 20],             "power" => 0,  "top" => 0, "left" => 0],
        18 => ["value" => 18, "adjacents" => [15, 16, 20, 21],     "power" => 0,  "top" => 0, "left" => 0],
        19 => ["value" => 19, "adjacents" => [16, 21],             "power" => 0,  "top" => 0, "left" => 0],
        20 => ["value" => 20, "adjacents" => [17, 18, 21, 22, 23], "power" => 0,  "top" => 0, "left" => 0],
        21 => ["value" => 21, "adjacents" => [18, 19, 20, 23, 24], "power" => 0,  "top" => 0, "left" => 0],
        22 => ["value" => 22, "adjacents" => [20, 25],             "power" => 51, "top" => 0, "left" => 0],
        23 => ["value" => 23, "adjacents" => [21, 24, 25, 41],     "power" => 0,  "top" => 0, "left" => 0],
        24 => ["value" => 24, "adjacents" => [21, 23],             "power" => 51, "top" => 0, "left" => 0],
        25 => ["value" => 25, "adjacents" => [20, 22, 23, 41],     "power" => 0,  "top" => 0, "left" => 0],
        41 => ["value" => 41, "adjacents" => [23, 25],             "power" => 0,  "top" => 0, "left" => 0],
    ],
    "carribean" => [
        1  => ["value" => 1,  "adjacents" => [11, 13],         "power" => 0, "top" => 0, "left" => 0],
        2  => ["value" => 2,  "adjacents" => [15],             "power" => 0, "top" => 0, "left" => 0],
        11 => ["value" => 11, "adjacents" => [1, 12, 14],      "power" => 0, "top" => 0, "left" => 0],
        12 => ["value" => 12, "adjacents" => [11, 15, 17, 21], "power" => 0, "top" => 0, "left" => 0],
        13 => ["value" => 13, "adjacents" => [1, 14],          "power" => 0, "top" => 0, "left" => 0],
        14 => ["value" => 14, "adjacents" => [11, 13, 16],     "power" => 0, "top" => 0, "left" => 0],
        15 => ["value" => 15, "adjacents" => [2, 12, 18],      "power" => 0, "top" => 0, "left" => 0],
        16 => ["value" => 16, "adjacents" => [14, 17, 19],     "power" => 0, "top" => 0, "left" => 0],
        17 => ["value" => 17, "adjacents" => [12, 16, 20],     "power" => 0, "top" => 0, "left" => 0],
        18 => ["value" => 18, "adjacents" => [15, 21],         "power" => 0, "top" => 0, "left" => 0],
        19 => ["value" => 19, "adjacents" => [16, 20, 22],     "power" => 0, "top" => 0, "left" => 0],
        20 => ["value" => 20, "adjacents" => [17, 19, 21, 41], "power" => 0, "top" => 0, "left" => 0],
        21 => ["value" => 21, "adjacents" => [12, 18, 20],     "power" => 0, "top" => 0, "left" => 0],
        22 => ["value" => 22, "adjacents" => [19, 41],         "power" => 0, "top" => 0, "left" => 0],
        41 => ["value" => 41, "adjacents" => [20, 22],         "power" => 0, "top" => 0, "left" => 0],
    ],
    "station" => [
        1  => ["value" => 1,  "adjacents" => [11, 12],                     "power" => 0, "top" => 0, "left" => 0],
        11 => ["value" => 11, "adjacents" => [1, 14, 15],                  "power" => 0, "top" => 0, "left" => 0],
        12 => ["value" => 12, "adjacents" => [1, 13, 15],                  "power" => 0, "top" => 0, "left" => 0],
        13 => ["value" => 13, "adjacents" => [12, 15, 16],                 "power" => 0, "top" => 0, "left" => 0],
        14 => ["value" => 14, "adjacents" => [11, 15, 18],                 "power" => 0, "top" => 0, "left" => 0],
        15 => ["value" => 15, "adjacents" => [11, 12, 13, 14, 16, 17, 18], "power" => 0, "top" => 0, "left" => 0],
        16 => ["value" => 16, "adjacents" => [13, 15, 17, 19, 20],         "power" => 0, "top" => 0, "left" => 0],
        17 => ["value" => 17, "adjacents" => [15, 16, 18, 19],             "power" => 0, "top" => 0, "left" => 0],
        18 => ["value" => 18, "adjacents" => [14, 15, 17, 19, 21],         "power" => 0, "top" => 0, "left" => 0],
        19 => ["value" => 19, "adjacents" => [16, 17, 18, 20, 21, 22, 23], "power" => 0, "top" => 0, "left" => 0],
        20 => ["value" => 20, "adjacents" => [16, 19, 23],                 "power" => 0, "top" => 0, "left" => 0],
        21 => ["value" => 21, "adjacents" => [18, 19, 22],                 "power" => 0, "top" => 0, "left" => 0],
        22 => ["value" => 22, "adjacents" => [19, 21, 41],                 "power" => 0, "top" => 0, "left" => 0],
        23 => ["value" => 23, "adjacents" => [19, 20, 41],                 "power" => 0, "top" => 0, "left" => 0],
        41 => ["value" => 41, "adjacents" => [22, 23],                     "power" => 0, "top" => 0, "left" => 0],
    ],
    "battlefield" => [
        1  => ["value" => 1,  "adjacents" => [11, 12],         "power" => 0,  "top" => 0, "left" => 0],
        11 => ["value" => 11, "adjacents" => [1, 13],          "power" => 0,  "top" => 0, "left" => 0],
        12 => ["value" => 12, "adjacents" => [1, 15],          "power" => 0,  "top" => 0, "left" => 0],
        13 => ["value" => 13, "adjacents" => [11, 14, 16, 17], "power" => 0,  "top" => 0, "left" => 0],
        14 => ["value" => 14, "adjacents" => [13, 15, 17, 18], "power" => 81, "top" => 0, "left" => 0],
        15 => ["value" => 15, "adjacents" => [14, 18, 19],     "power" => 0,  "top" => 0, "left" => 0],
        16 => ["value" => 16, "adjacents" => [13, 20],         "power" => 81, "top" => 0, "left" => 0],
        17 => ["value" => 17, "adjacents" => [13, 14, 20, 21], "power" => 0,  "top" => 0, "left" => 0],
        18 => ["value" => 18, "adjacents" => [14, 15, 21, 22], "power" => 0,  "top" => 0, "left" => 0],
        19 => ["value" => 19, "adjacents" => [15, 22],         "power" => 81, "top" => 0, "left" => 0],
        20 => ["value" => 20, "adjacents" => [16, 17, 21, 23], "power" => 0,  "top" => 0, "left" => 0],
        21 => ["value" => 21, "adjacents" => [17, 18, 20, 22], "power" => 81, "top" => 0, "left" => 0],
        22 => ["value" => 22, "adjacents" => [18, 19, 21, 24], "power" => 0,  "top" => 0, "left" => 0],
        23 => ["value" => 23, "adjacents" => [20, 41],         "power" => 0,  "top" => 0, "left" => 0],
        24 => ["value" => 24, "adjacents" => [22, 41],         "power" => 0,  "top" => 0, "left" => 0],
        41 => ["value" => 41, "adjacents" => [23, 24],         "power" => 0,  "top" => 0, "left" => 0],
    ],
];

$this->_regions = [
    "castle" => [
        1 => ["value" => 1, "bases" => [11, 12, 13, 14, 18],  "medals" => 3],
        2 => ["value" => 2, "bases" => [13, 15, 17],          "medals" => 1],
        3 => ["value" => 3, "bases" => [14, 16, 19],          "medals" => 1],
        4 => ["value" => 4, "bases" => [13, 17, 18, 22],      "medals" => 2],
        5 => ["value" => 5, "bases" => [14, 18, 19, 23],      "medals" => 2],
        6 => ["value" => 6, "bases" => [17, 20, 22],          "medals" => 1],
        7 => ["value" => 7, "bases" => [19, 21, 23],          "medals" => 1],
        8 => ["value" => 8, "bases" => [18, 22, 23, 24, 25],  "medals" => 3],
    ],
    "pool" => [
        1 => ["value" => 1, "bases" => [11, 12, 13],     "medals" => 1],
        2 => ["value" => 2, "bases" => [12, 13, 15, 17], "medals" => 2],
        3 => ["value" => 3, "bases" => [13, 14, 17],     "medals" => 1],
        4 => ["value" => 4, "bases" => [14, 16, 17, 19], "medals" => 2],
        5 => ["value" => 5, "bases" => [15, 17, 18, 20], "medals" => 2],
        6 => ["value" => 6, "bases" => [17, 20, 21],     "medals" => 1],
        7 => ["value" => 7, "bases" => [17, 19, 21, 22], "medals" => 2],
        8 => ["value" => 8, "bases" => [21, 22, 23],     "medals" => 1],
    ],
    "clouds" => [
        1 => ["value" => 1,   "bases" => [11, 12, 13],     "medals" => 1],
        2 => ["value" => 2,   "bases" => [11, 13, 14],     "medals" => 1],
        3 => ["value" => 3,   "bases" => [12, 13, 15],     "medals" => 1],
        4 => ["value" => 4,   "bases" => [13, 14, 15, 16], "medals" => 2],
        5 => ["value" => 5,   "bases" => [14, 16, 17],     "medals" => 1],
        6 => ["value" => 6,   "bases" => [15, 16, 18],     "medals" => 1],
        7 => ["value" => 7,   "bases" => [16, 17, 18, 19], "medals" => 2],
        8 => ["value" => 8,   "bases" => [17, 19, 20],     "medals" => 1],
        9 => ["value" => 9,   "bases" => [18, 19, 21],     "medals" => 1],
        10 => ["value" => 10, "bases" => [19, 20, 21, 22], "medals" => 2],
        11 => ["value" => 11, "bases" => [20, 22, 23],     "medals" => 1],
        12 => ["value" => 12, "bases" => [21, 22, 24],     "medals" => 1],
        13 => ["value" => 13, "bases" => [22, 23, 24],     "medals" => 1],
    ],
    "jungle" => [
        1 => ["value" => 1, "bases" => [11, 13, 14, 16, 17], "medals" => 3],
        2 => ["value" => 2, "bases" => [11, 12, 14, 15],     "medals" => 2],
        3 => ["value" => 3, "bases" => [14, 15, 17, 18],     "medals" => 2],
        4 => ["value" => 4, "bases" => [16, 17, 19, 20],     "medals" => 2],
        5 => ["value" => 5, "bases" => [17, 18, 20, 21, 23], "medals" => 3],
        6 => ["value" => 6, "bases" => [19, 20, 22, 23],     "medals" => 2],
    ],
    "cemetery" => [
        1 => ["value" => 1,  "bases" => [11, 14, 16],     "medals" => 1],
        2 => ["value" => 2,  "bases" => [11, 13, 15, 16], "medals" => 2],
        3 => ["value" => 3,  "bases" => [12, 13, 15],     "medals" => 1],
        4 => ["value" => 4,  "bases" => [15, 16, 18],     "medals" => 1],
        5 => ["value" => 5,  "bases" => [15, 17, 18, 20], "medals" => 2],
        6 => ["value" => 6,  "bases" => [16, 18, 19, 21], "medals" => 2],
        7 => ["value" => 7,  "bases" => [18, 20, 21],     "medals" => 1],
        8 => ["value" => 8,  "bases" => [20, 22, 25],     "medals" => 1],
        9 => ["value" => 9,  "bases" => [20, 21, 23, 25], "medals" => 2],
        10 => ["value" => 10, "bases" => [21, 23, 24],    "medals" => 1],
    ],
    "carribean" => [
        1 => ["value" => 1, "bases" => [11, 13, 14],         "medals" => 1],
        2 => ["value" => 2, "bases" => [11, 12, 14, 16, 17], "medals" => 3],
        3 => ["value" => 3, "bases" => [12, 15, 18, 21],     "medals" => 2],
        4 => ["value" => 4, "bases" => [12, 17, 20, 21],     "medals" => 2],
        5 => ["value" => 5, "bases" => [16, 17, 19, 20],     "medals" => 2],
        6 => ["value" => 6, "bases" => [19, 20, 22],         "medals" => 1],
    ],
    "station" => [
        1 => ["value" => 1,   "bases" => [11, 12, 15],  "medals" => 1],
        2 => ["value" => 2,   "bases" => [11, 14, 15],  "medals" => 1],
        3 => ["value" => 3,   "bases" => [12, 13, 15],  "medals" => 1],
        4 => ["value" => 4,   "bases" => [13, 15, 16],  "medals" => 1],
        5 => ["value" => 5,   "bases" => [14, 15, 18],  "medals" => 1],
        6 => ["value" => 6,   "bases" => [15, 16, 17],  "medals" => 1],
        7 => ["value" => 7,   "bases" => [15, 17, 18],  "medals" => 1],
        8 => ["value" => 8,   "bases" => [16, 17, 19],  "medals" => 1],
        9 => ["value" => 9,   "bases" => [17, 18, 19],  "medals" => 1],
        10 => ["value" => 10, "bases" => [16, 19, 20],  "medals" => 1],
        11 => ["value" => 11, "bases" => [18, 19, 21],  "medals" => 1],
        12 => ["value" => 12, "bases" => [19, 20, 23],  "medals" => 1],
        13 => ["value" => 13, "bases" => [19, 21, 22],  "medals" => 1],
        14 => ["value" => 14, "bases" => [19, 22, 23],  "medals" => 1],
    ],
    "battlefield" => [
        1 => ["value" => 1,  "bases" => [11, 12, 13, 14, 15],  "medals" => 3],
        2 => ["value" => 2,  "bases" => [13, 14, 17],          "medals" => 1],
        3 => ["value" => 3,  "bases" => [14, 15, 18],          "medals" => 1],
        4 => ["value" => 4,  "bases" => [13, 16, 17, 20],      "medals" => 2],
        5 => ["value" => 5,  "bases" => [14, 17, 18, 21],      "medals" => 2],
        6 => ["value" => 6,  "bases" => [15, 18, 19, 22],      "medals" => 2],
        7 => ["value" => 7,  "bases" => [17, 20, 21],          "medals" => 1],
        8 => ["value" => 8,  "bases" => [18, 21, 22],          "medals" => 1],
        9 => ["value" => 9,  "bases" => [20, 21, 22, 23, 24],  "medals" => 3],
    ],
];

$this->_medals = [
    "castle" => [
        1 => ["region" => 1, "top" => 68.3, "left" => 48.9],
        2 => ["region" => 1, "top" => 69.9, "left" => 48.9],
        3 => ["region" => 1, "top" => 71.5, "left" => 48.9],
        4 => ["region" => 2, "top" => 69.9, "left" => 24.4],
        5 => ["region" => 3, "top" => 69.9, "left" => 73.4],
        6 => ["region" => 4, "top" => 49.3, "left" => 33.9],
        7 => ["region" => 4, "top" => 50.9, "left" => 33.9],
        8 => ["region" => 5, "top" => 49.3, "left" => 64.1],
        9 => ["region" => 5, "top" => 51, "left" => 64.1],
        10 => ["region" => 6, "top" => 29.4, "left" => 24.4],
        11 => ["region" => 7, "top" => 29.4, "left" => 73.4],
        12 => ["region" => 8, "top" => 27.7, "left" => 48.9],
        13 => ["region" => 8, "top" => 29.3, "left" => 48.9],
        14 => ["region" => 8, "top" => 31, "left" => 48.9]
    ],
    "pool" => [
        1 => ["region" => 1, "top" => 0, "left" => 0],
        2 => ["region" => 2, "top" => 0, "left" => 0],
        3 => ["region" => 2, "top" => 0, "left" => 0],
        4 => ["region" => 3, "top" => 0, "left" => 0],
        5 => ["region" => 4, "top" => 0, "left" => 0],
        6 => ["region" => 4, "top" => 0, "left" => 0],
        7 => ["region" => 5, "top" => 0, "left" => 0],
        8 => ["region" => 5, "top" => 0, "left" => 0],
        9 => ["region" => 6, "top" => 0, "left" => 0],
        10 => ["region" => 7, "top" => 0, "left" => 0],
        11 => ["region" => 7, "top" => 0, "left" => 0],
        12 => ["region" => 8, "top" => 0, "left" => 0]
    ],
    "clouds" => [
        1 => ["region" =>  1, "top" => 0, "left" => 0],
        2 => ["region" =>  2, "top" => 0, "left" => 0],
        3 => ["region" =>  3, "top" => 0, "left" => 0],
        4 => ["region" =>  4, "top" => 0, "left" => 0],
        5 => ["region" =>  4, "top" => 0, "left" => 0],
        6 => ["region" =>  5, "top" => 0, "left" => 0],
        7 => ["region" =>  6, "top" => 0, "left" => 0],
        8 => ["region" =>  7, "top" => 0, "left" => 0],
        9 => ["region" =>  7, "top" => 0, "left" => 0],
        10 => ["region" =>  8, "top" => 0, "left" => 0],
        11 => ["region" =>  9, "top" => 0, "left" => 0],
        12 => ["region" => 10, "top" => 0, "left" => 0],
        13 => ["region" => 10, "top" => 0, "left" => 0],
        14 => ["region" => 11, "top" => 0, "left" => 0],
        15 => ["region" => 12, "top" => 0, "left" => 0],
        16 => ["region" => 13, "top" => 0, "left" => 0]
    ],
    "jungle" => [
        1 => ["region" => 1, "top" => 0, "left" => 0],
        2 => ["region" => 1, "top" => 0, "left" => 0],
        3 => ["region" => 1, "top" => 0, "left" => 0],
        4 => ["region" => 2, "top" => 0, "left" => 0],
        5 => ["region" => 2, "top" => 0, "left" => 0],
        6 => ["region" => 3, "top" => 0, "left" => 0],
        7 => ["region" => 3, "top" => 0, "left" => 0],
        8 => ["region" => 4, "top" => 0, "left" => 0],
        9 => ["region" => 4, "top" => 0, "left" => 0],
        10 => ["region" => 5, "top" => 0, "left" => 0],
        11 => ["region" => 5, "top" => 0, "left" => 0],
        12 => ["region" => 5, "top" => 0, "left" => 0],
        13 => ["region" => 6, "top" => 0, "left" => 0],
        14 => ["region" => 6, "top" => 0, "left" => 0]
    ],
    "cemetery" => [
        1 => ["region" =>  1, "top" => 0, "left" => 0],
        2 => ["region" =>  2, "top" => 0, "left" => 0],
        3 => ["region" =>  2, "top" => 0, "left" => 0],
        4 => ["region" =>  3, "top" => 0, "left" => 0],
        5 => ["region" =>  4, "top" => 0, "left" => 0],
        6 => ["region" =>  5, "top" => 0, "left" => 0],
        7 => ["region" =>  5, "top" => 0, "left" => 0],
        8 => ["region" =>  6, "top" => 0, "left" => 0],
        9 => ["region" =>  6, "top" => 0, "left" => 0],
        10 => ["region" =>  7, "top" => 0, "left" => 0],
        11 => ["region" =>  8, "top" => 0, "left" => 0],
        12 => ["region" =>  9, "top" => 0, "left" => 0],
        13 => ["region" =>  9, "top" => 0, "left" => 0],
        14 => ["region" => 10, "top" => 0, "left" => 0]
    ],
    "carribean" => [
        1 => ["region" =>  1, "top" => 0, "left" => 0],
        2 => ["region" =>  2, "top" => 0, "left" => 0],
        3 => ["region" =>  2, "top" => 0, "left" => 0],
        4 => ["region" =>  2, "top" => 0, "left" => 0],
        5 => ["region" =>  3, "top" => 0, "left" => 0],
        6 => ["region" =>  3, "top" => 0, "left" => 0],
        7 => ["region" =>  4, "top" => 0, "left" => 0],
        8 => ["region" =>  4, "top" => 0, "left" => 0],
        9 => ["region" =>  5, "top" => 0, "left" => 0],
        10 => ["region" =>  5, "top" => 0, "left" => 0],
        11 => ["region" =>  6, "top" => 0, "left" => 0]
    ],
    "station" => [
        1 => ["region" =>  1, "top" => 0, "left" => 0],
        2 => ["region" =>  2, "top" => 0, "left" => 0],
        3 => ["region" =>  3, "top" => 0, "left" => 0],
        4 => ["region" =>  4, "top" => 0, "left" => 0],
        5 => ["region" =>  5, "top" => 0, "left" => 0],
        6 => ["region" =>  6, "top" => 0, "left" => 0],
        7 => ["region" =>  7, "top" => 0, "left" => 0],
        8 => ["region" =>  8, "top" => 0, "left" => 0],
        9 => ["region" =>  9, "top" => 0, "left" => 0],
        10 => ["region" => 10, "top" => 0, "left" => 0],
        11 => ["region" => 11, "top" => 0, "left" => 0],
        12 => ["region" => 12, "top" => 0, "left" => 0],
        13 => ["region" => 13, "top" => 0, "left" => 0],
        14 => ["region" => 14, "top" => 0, "left" => 0]
    ],
    "battlefield" => [
        1 => ["region" => 1, "top" => 0, "left" => 0],
        2 => ["region" => 1, "top" => 0, "left" => 0],
        3 => ["region" => 1, "top" => 0, "left" => 0],
        4 => ["region" => 2, "top" => 0, "left" => 0],
        5 => ["region" => 3, "top" => 0, "left" => 0],
        6 => ["region" => 4, "top" => 0, "left" => 0],
        7 => ["region" => 4, "top" => 0, "left" => 0],
        8 => ["region" => 5, "top" => 0, "left" => 0],
        9 => ["region" => 5, "top" => 0, "left" => 0],
        10 => ["region" => 6, "top" => 0, "left" => 0],
        11 => ["region" => 6, "top" => 0, "left" => 0],
        12 => ["region" => 7, "top" => 0, "left" => 0],
        13 => ["region" => 8, "top" => 0, "left" => 0],
        14 => ["region" => 9, "top" => 0, "left" => 0],
        15 => ["region" => 9, "top" => 0, "left" => 0],
        16 => ["region" => 9, "top" => 0, "left" => 0]
    ],
];


$this->_powers = [[], [11], [21, 23, 26], [31],  [41], [51], [], [], [81]];

$this->_medals_to_win = [-1, 7, 6, 8, 7, 7, 5, 7, 8];
